version: '3'

services:
  app:
    build: .
    container_name: micro-videos-python-app
    command: ./.docker/entrypoint.sh
    volumes:
      - .:/home/python/app
    ports:
      - 8000:8000